load_balancer:
  name: lb 
  algorithm: pewma
  port: 8888
  servers:
    - name: server1
      address: 192.168.1.1
      port: 80
      weight: 1
    - name: server2
      address: 192.168.1.2
      port: 80
      weight: 1
    - name: server3
      address: 192.168.1.3
      port: 80
      weight: 1
  health_check:
    interval: 30s
    timeout: 5s
    retries: 3
    path: /health
    method: GET
